In [1]:
import pandas as pd

In [19]:
data_excel = pd.read_excel(
    "data/ametnike_palgad_2018.xlsx", 
    sheet_name=3, 
    header=6, 
    skiprows=[7]
)
data_excel

,Asutus,Struktuuriüksus,Ametikoht,Eesnimi,Perekonnanimi,Ametniku koormus ametikohal,"Põhipalk, sh puhkusetasu",Muutuvpalk,Muu tulu,Kokku (7+8+9),Periood,Ametniku ametikoht muutus
0,Andmekaitse Inspektsioon,Andmekaitse Inspektsioon,Peadirektor,Viljar,Peep,1.0,32099.17,3000.00,NaN,35099.17,01.01.2018-30.09.2018,NaN
1,Andmekaitse Inspektsioon,Andmekaitse Inspektsioon,õigusdirektor,Raavo,Palu,1.0,30989.79,6150.00,NaN,37139.79,01.01.2018-31.12.2018,NaN
2,Andmekaitse Inspektsioon,Andmekaitse Inspektsioon,arendusdirektor,Kaja,Puusepp,1.0,29242.28,5726.40,NaN,34968.68,01.01.2018-31.12.2018,NaN
3,Andmekaitse Inspektsioon,Andmekaitse Inspektsioon,peainspektor,Elve,Adamson,1.0,27209.31,5412.00,NaN,32621.31,01.01.2018-31.12.2018,NaN
4,Andmekaitse Inspektsioon,Andmekaitse Inspektsioon,Juhtivinspektor,Merit,Valgjärv,1.0,7501.70,NaN,NaN,7501.70,01.01.2018-24.04.2018,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
13157,Vabariigi Presidendi Kantselei,NaN,VP digiühiskona nõunik,Margus,Mägi,1.0,13909.09,2250.00,0.00,16159.09,13.08.2018-31.12.2018,NaN
13158,Vabariigi Presidendi Kantselei,Välisosakond,Välisosakonna juhataja,Kristel,Lõuk,1.0,32824.42,4780.00,327.27,37931.69,01.01.2018-31.12.2018,NaN
13159,Vabariigi Presidendi Kantselei,Siseosakond,Siseosakonna juhataja,Erki,Holmberg,1.0,34851.35,5796.58,1018.79,41666.72,01.01.2018-31.12.2018,NaN
13160,Vabariigi Presidendi Kantselei,Siseosakond,juhataja asetäitja,Mall,Gramberg,1.0,29957.47,5000.00,0.00,34957.47,01.01.2018-31.12.2018,NaN
13161,Vabariigi Presidendi Kantselei,NaN,VP nõunik-abi,Triin,Väljataga,1.0,24476.40,4050.00,0.00,28526.40,01.01.2018-31.12.2018,NaN

In [26]:
data_csv = pd.read_csv(
    'data/keskmine_brutopalk.csv',
    header=1
)
data_csv

,Näitaja,Tegevusala,2018,2018 I kvartal,2018 II kvartal,2018 III kvartal,2018 IV kvartal,2019,2019 I kvartal,2019 II kvartal,...,2020,2020 I kvartal,2020 II kvartal,2020 III kvartal,2020 IV kvartal,2021,2021 I kvartal,2021 II kvartal,2021 III kvartal,2021 IV kvartal
0,"Keskmine brutokuupalk, eurot",Kokku – kõik tegevusalad,1310,1242.0,1321.0,1291.0,1384.0,1407,1341.0,1419.0,...,1448,1404.0,1433.0,1441.0,1515.0,1548,1473.0,1538.0,1553.0,1625.0
1,"Keskmine brutokuupalk, eurot","Põllumajandus, metsamajandus ja kalapüük",1163,1133.0,1151.0,1167.0,1201.0,1141,1121.0,1104.0,...,1202,1159.0,1154.0,1222.0,1279.0,1294,1270.0,1288.0,1263.0,1354.0
2,"Keskmine brutokuupalk, eurot",Mäetööstus,1606,1547.0,1615.0,1594.0,1670.0,1638,1667.0,1658.0,...,1697,1699.0,1588.0,1677.0,1847.0,1840,1732.0,1869.0,1847.0,1908.0
3,"Keskmine brutokuupalk, eurot",Töötlev tööstus,1249,1189.0,1266.0,1234.0,1307.0,1339,1277.0,1354.0,...,1363,1342.0,1336.0,1373.0,1404.0,1440,1377.0,1430.0,1462.0,1491.0
4,"Keskmine brutokuupalk, eurot","Elektrienergia, gaasi, auru ja konditsioneerit...",1857,2101.0,1823.0,1719.0,1790.0,1996,2264.0,1913.0,...,2118,2338.0,2118.0,1977.0,2035.0,2128,2295.0,2124.0,2007.0,2084.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,"Brutopalga kogusumma jaotus, %",Avalik haldus ja riigikaitse; kohustuslik sots...,7,7.0,7.0,7.0,8.0,8,7.0,8.0,...,9,8.0,9.0,9.0,9.0,8,8.0,8.0,8.0,8.0
476,"Brutopalga kogusumma jaotus, %",Haridus,9,9.0,9.0,8.0,10.0,9,9.0,9.0,...,11,10.0,11.0,10.0,11.0,9,10.0,10.0,9.0,10.0
477,"Brutopalga kogusumma jaotus, %",Tervishoid ja sotsiaalhoolekanne,7,7.0,7.0,7.0,7.0,7,7.0,7.0,...,8,8.0,9.0,9.0,9.0,8,8.0,9.0,8.0,8.0
478,"Brutopalga kogusumma jaotus, %","Kunst, meelelahutus ja vaba aeg",2,2.0,2.0,2.0,2.0,2,2.0,2.0,...,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0,2.0
479,"Brutopalga kogusumma jaotus, %",Muud teenindavad tegevused,1,1.0,1.0,1.0,1.0,1,1.0,1.0,...,1,1.0,1.0,1.0,1.0,2,2.0,2.0,2.0,2.0